config/routes.rb
DeePoh::Application.routes.draw do
  
  resources :workers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/login', to: 'sessions#new'
  

  resources :depots do
    resources :packages
  end
  
  resources :packages do
    resources :artifacts
  end
    
  
  
  resources :depots
  match '/depots/new', to: 'depots#new'
    
  resources :packages
  match '/packages/new', to: 'packages#new'
  
  resources :artifacts
  match '/artifacts/new', to: 'artifacts#new'
  
  resources :users
  match '/users/new', to: 'users#new'
  
  resources :roles
  match '/roles/new', to: 'roles#new'
  
  resources :credentials
  match '/credentials/new', to: 'credentials#new'
  
  resources :engines
  match '/engines/new', to: 'engines#new'
    
  resources :workers
  match '/workers/new', to: 'workers#new'
  

end

app/models/engine.rb
class Engine < ActiveRecord::Base
  attr_accessible :eng_description, :eng_host, :eng_name, :eng_threads, :eng_type
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @engines }
    end
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
    @engine = Engine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @engine }
    end
  end

  # GET /engines/new
  # GET /engines/new.json
  def new
    @engine = Engine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @engine }
    end
  end

  # GET /engines/1/edit
  def edit
    @engine = Engine.find(params[:id])
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(params[:engine])

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render json: @engine, status: :created, location: @engine }
      else
        format.html { render action: "new" }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /engines/1
  # PUT /engines/1.json
  def update
    @engine = Engine.find(params[:id])

    respond_to do |format|
      if @engine.update_attributes(params[:engine])
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine = Engine.find(params[:id])
    @engine.destroy

    respond_to do |format|
      format.html { redirect_to engines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<%= form_for(@engine) do |f| %>

  <% if @engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engine.errors.count, "error") %> <%= t('.error01') %></h2>

      <ul>
      <% @engine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
  <tr>
    <td align="right" style="width:150px"><%= f.label t('.engine_name') %></td>
    <td><%= f.text_field :eng_name, :autofocus => true %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right" style="width:100px"><%= f.label t('.engine_desc') %></td>
    <td><%= f.text_field :eng_description %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right" style="width:100px"><%= f.label t('.engine_type') %></td>
    <td><%= f.text_field :eng_type %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right" style="width:100px"><%= f.label t('.engine_host') %></td>
    <td><%= f.text_field :eng_host %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right" style="width:100px"><%= f.label t('.engine_threads') %></td>
    <td><%= f.text_field :eng_threads %></td>
  </tr>
  </table>
  
  <br>
  <button type="submit" class="btn btn-primary"><%= t('.submit') %></button>
  <br>
  <%= link_to t('.cancel'), engines_path %>

<% end %>

app/views/engines/edit.html.erb
  
<h2><%= t('.edit_engine') %></h2><br>

<% unless notice.nil? %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<%= render 'form' %>

</div>

app/views/engines/index.html.erb
<h3><%= image_tag( "servers.png", :border => 0, :valign => "middle" ) %> <%= t('.engines') %> <%= link_to image_tag('tooltip12x12.png', :border => 0, :align => "top"), nil, title: t('.engines_tooltip'), rel: 'popover' %></h3>


<% unless notice.nil? %>
  <div class="container center alert alert-success"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="alert"><%= flash[:alert] %></p>
  </div>
<% end %>

<table class="table table-striped table-bordered table-condensed">
  <tr style="background-color: #44721e">
    <th style="background-color: #91b96f"><%= sortable t('.engine_name') %></th>
    <th style="background-color: #91b96f"><%= sortable t('.engine_desc') %></th>
    <th style="background-color: #91b96f"><%= sortable t('.engine_type') %></th></th>
    <th style="background-color: #91b96f"><%= sortable t('.engine_host') %></th>
    <th style="background-color: #91b96f"><%= sortable t('.engine_threads') %></th>

    <th style="text-align: center; background-color: #91b96f" colspan=3><%= t('.actions') %></th>
  </tr>

<% @engines.each do |engine| %>
  <tr>
    <td><%= engine.eng_name %></td>
    <td><%= engine.eng_description %></td>
    <td><%= engine.eng_type %></td>
    <td><%= engine.eng_host %></td>
    <td><%= engine.eng_threads %></td>

    <td style="text-align: center;width:30px"><%= link_to t('.show'), engine %></td>
    <td style="text-align: center;width:30px""><%= link_to t('.edit'), edit_engine_path(engine) %></td>
    <td style="text-align: center;width:30px""><%= link_to t('.destroy'), engine, confirm: t('.confirm'), method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= button_to t('.new_engine'), new_engine_path , :class => "btn btn-primary btn-mini" %>

app/views/engines/new.html.erb
<h2><%= t('.add_engine') %></h2><br>

<%= render 'form' %>

app/views/engines/show.html.erb
<h2><%= t('.engine_details') %></h2><br>

<% unless notice.nil? %>
  <div class="container center alert alert-success"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<table class="table table-striped table-bordered table-condensed">
<tr>
  <td align="right" style="width:200px"><b><%= t('.engine_name') %></b></td>
  <td><%= @engine.eng_name %></td>
</tr>
<tr>
  <td align="right" style="width:200px"><b><%= t('.engine_desc') %></b></td>
  <td><%= @engine.eng_description %></td>
</tr>
<tr>
  <td align="right" style="width:200px"><b><%= t('.engine_type') %></b></td>
  <td><%= @engine.eng_type %></td>
</tr>
<tr>
  <td align="right" style="width:200px"><b><%= t('.engine_host') %></b></td>
  <td><%= @engine.eng_host %></td>
</tr>
<tr>
  <td align="right" style="width:200px"><b><%= t('.engine_threads') %></b></td>
  <td><%= @engine.eng_threads %></td>
</tr>
</table>

<%= link_to t('.edit_engine'), edit_engine_path(@engine), :class=>'btn btn-primary btn-mini' %>

<br>
<%= link_to t('.back'), engines_path %>