config/routes.rb
DeePoh::Application.routes.draw do
  
  resources :workers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/login', to: 'sessions#new'
  

  resources :depots do
    resources :packages
  end
  
  resources :packages do
    resources :artifacts
  end
    
  
  
  resources :depots
  match '/depots/new', to: 'depots#new'
    
  resources :packages
  match '/packages/new', to: 'packages#new'
  
  resources :artifacts
  match '/artifacts/new', to: 'artifacts#new'
  
  resources :users
  match '/users/new', to: 'users#new'
  
  resources :roles
  match '/roles/new', to: 'roles#new'
  
  resources :credentials
  match '/credentials/new', to: 'credentials#new'
  
  resources :engines
  match '/engines/new', to: 'engines#new'
    
  resources :workers
  match '/workers/new', to: 'workers#new'
  

end

app/views/shared/_nav.html.erb
<ul class="nav nav-tabs">
  <li <% if defined?(home) && home %>class="active"<% end %>><%= link_to t('.tab_home'), home_path %></li>
  <li <% if defined?(depots) && depots %>class="active"<% end %>><%= link_to t('.tab_depots'), depots_path %></li>
  <li <% if defined?(users) && users %>class="active"<% end %>><%= link_to t('.tab_users'), users_path %></li>
  <li <% if defined?(roles) && roles %>class="active"<% end %>><%= link_to t('.tab_roles'), roles_path %></li>
  <li <% if defined?(credentials) && credentials %>class="active"<% end %>><%= link_to t('.tab_credentials'), credentials_path %></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('.tab_dropdown') %><b class="caret"></b></a>
     <ul class="dropdown-menu">
      <li><a href="#">Action</a></li>
      <li><a href="#">Another action</a></li>
      <li><a href="#">Something else here</a></li>
      <li class="divider"></li>
      <li><a href="#">Separated link</a></li>
    </ul>
  </li>
</ul>

app/views/shared/_nav_sidebar.html.erb
<% if (session[:user_role] != nil) %>
  
  <ul class="nav nav-list well">
    <li class="nav-header">Depot</li>
  <li><%= link_to image_tag( "home.png", :border => 0, :align => "top" ) + " " + t('.tab_home'), home_path %></li>
   <li><%= link_to image_tag( "reports.png", :border => 0, :align => "top" ) + " " + t('.tab_reports'), home_path %></li>
  <br/>
  
  <li class="nav-header">Depots</li>
  <ul class="nav">
  <li><%= link_to image_tag( "depots.png", :border => 0, :align => "top" ) + " " + t('.tab_projects'), depots_path %></li>
  </ul>
  
  <% if (session[:user_role] == "admin") || (session[:user_role] == "manager") %>
    <li class="nav-header">Access</li>
    <ul class="nav">
    <li><%= link_to image_tag( "users.png", :border => 0, :align => "top" ) + " " + t('.tab_users'), users_path %></li>
    <li><%= link_to image_tag( "roles.png", :border => 0, :align => "top" ) + " " + t('.tab_roles'), roles_path %></li>
    <li><%= link_to image_tag( "creds1.png", :border => 0, :align => "top" ) + " " + t('.tab_credentials'), credentials_path %></li>
    </ul>
  <% end %>
  
  <% if session[:user_role] == "admin" %>
    <li class="nav-header">Administration</li>
    <ul class="nav">
    <li><%= link_to image_tag( "servers.png", :border => 0, :align => "top" ) + " " + t('.tab_engines'), engines_path %></li>
    <li><%= link_to image_tag( "workers.png", :border => 0, :align => "top" ) + " " + t('.tab_workers'), workers_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= image_tag( "settings.png", :border => 0, :align => "top" ) %> <%= t('.tab_settings') %><b class="caret"></b></a>
       <ul class="dropdown-menu">
        <li><%= link_to image_tag( "servers.png", :border => 0, :align => "top" ) + " " + 'Database Servers', home_path %></li>
        <li><%= link_to image_tag( "drivers.png", :border => 0, :align => "top" ) + " " + 'Database Drivers', home_path %></li>
        <li class="divider"></li>
        <li><%= link_to t('.tab_home'), home_path %></li>
        
        <li class="divider"></li>
        <li><%= link_to t('.tab_home'), home_path %></li>
      </ul>
    </li>
    </ul>
  <% end %>
<% end %>