config/routes.rb
DeePoh::Application.routes.draw do
  
  resources :workers

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/login', to: 'sessions#new'
  

  resources :depots do
    resources :packages
  end
  
  resources :packages do
    resources :artifacts
  end
    
  
  
  resources :depots
  match '/depots/new', to: 'depots#new'
    
  resources :packages
  match '/packages/new', to: 'packages#new'
  
  resources :artifacts
  match '/artifacts/new', to: 'artifacts#new'
  
  resources :users
  match '/users/new', to: 'users#new'
  
  resources :roles
  match '/roles/new', to: 'roles#new'
  
  resources :credentials
  match '/credentials/new', to: 'credentials#new'
  
  resources :engines
  match '/engines/new', to: 'engines#new'
    
  resources :workers
  match '/workers/new', to: 'workers#new'
  

end

app/models/depot.rb
# == Schema Information
#
# Table name: depots
#
#  id         :integer         not null, primary key
#  dep_name   :string(255)
#  dep_desc   :string(255)
#  dep_status :integer
#  dep_type   :integer
#  dep_url    :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Depot < ActiveRecord::Base
  attr_accessible :dep_name, :dep_desc, :dep_type, :dep_url, :dep_status
  
  validates :dep_name, length: { minimum: 4 }, :presence => true
  validates :dep_desc, :dep_type,:dep_status, :presence => true
  
  has_many :packages, :dependent => :destroy

end

app/controllers/depots_controller.rb
class DepotsController < ApplicationController
  
  def index
    #@depots = Depot.order(sort_column + ' ' + sort_direction)
    @depots = Depot.find(:all, :order => 'dep_name')
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @depots }
    end
  end

  def show
    @depot = Depot.find(params[:id])
    add_breadcrumb "Depots", depots_path

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @depot }
    end
  end

  def new
    @depot = Depot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @depot }
    end
  end

  def edit
    @depot = Depot.find(params[:id])
  end

  def create
    @depot = Depot.new(params[:depot])
    
    respond_to do |format|    
      if @depot.save
        depot_url = @depot.dep_name
        depot_url = depot_url[0, 24]
        depot_url = depot_url.gsub(' ', '_')
        depot_url = depot_url + "_" + "#{@depot.id}".to_s
        @depot.dep_url = depot_url
        @depot.save
        dir = DEPOT_ROOT + "/" + "#{depot_url}"
        # make sure no goofy chars in string
        special = "?<>.',?[]}{=-)(*&^%$#`~{}"
        regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
        #
        # if find.byname(@depot.dep_name) is true
        # error depot names must be unique
        #
        if depot_url =~ regex
          @depot.destroy
          format.html { redirect_to depots_url, :alert => "ERROR: Illegal characters in name." }
          format.json { head :no_content }
        else
          Logg3r.info Time.now.to_s + " - creating depot: " + depot_url + " at " + dir
          FileUtils.mkdir dir
          format.html { redirect_to @depot, notice: t(:depot_created) }
          format.json { render json: @depot, status: :created, location: @depot }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @depot.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @depot = Depot.find(params[:id])

    respond_to do |format|
      if @depot.update_attributes(params[:depot])
        format.html { redirect_to @depot, notice: t(:depot_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @depot.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @depot = Depot.find(params[:id])
    depot_url = @depot.dep_url

    dir = DEPOT_ROOT + "/" + "#{depot_url}"
    
    respond_to do |format|
      if FileTest.exists?(dir)
        Logg3r.info Time.now.to_s + " - destroying depot: " + depot_url + " at " + dir
        FileUtils.rm_r dir
        @depot.destroy
        format.html { redirect_to depots_url, :notice => t(:depot_deleted) }
        format.json { head :no_content }
      else
        format.html { redirect_to depots_url, :alert => "INTERNAL ERROR: Cannot locate depot at: #{dir}" }
        format.json { head :no_content }
      end
    end
  end
  
end

app/helpers/depots_helper.rb
module DepotsHelper
  
  STATUS = {'Online' => 1, 'Offline' => 2, 'Service' => 3}
  TYPE   = {'Local' => 1, 'Remote' => 2, 'Proxy' => 3}
    
  def get_DepotStatusText(depot_status)
    status = STATUS.index(depot_status)
    if status == "Online"
      "<span class='label label-success'>#{status}</span>"
    elsif status == "Offline"
      "<span class='label label-important'>#{status}</span>"
    elsif status == "Service"
      "<span class='label label-warning'>#{status}</span>"
    end
  end
  
  def get_DepotTypeText(depot_type)
    type = TYPE.index(depot_type)
    "<span class='label label-default'>#{type}</span>"
  end
  
  def user_HasCredToDepot(depot_id, user_id)
    @user = User.find_by_name(user_id)
    user_id = @user.id
    cred = Credential.find(:all, :conditions => {:depot_id => depot_id, :user_id => user_id})
    if cred == []
      return false
    else
      return true
    end
  end
  
  def user_HasWriteAccess(depot_id, user_id)
    @user = User.find_by_name(user_id)
    user_id = @user.id
    @cred = Credential.find(:all, :conditions => {:depot_id => depot_id, :user_id => user_id})
    role_id = @cred[0][:role_id]
    role = Role.find_by_id(role_id)
    if role.write == 1
      return true
    else
      return false
    end
  end
  
    def user_HasCanCreateDepot(user_id)
    @user = User.find_by_name(user_id)
    role_id = @user.role_id
    role = Role.find_by_id(role_id)
    if role.write == 1
      return true
    else
      return false
    end
  end
  
end

app/views/depots/_form.html.erb
<%= form_for(@depot) do |f| %>

  <% if @depot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@depot.errors.count, "error") %> <%= t('.error01') %></h2>

      <ul>
      <% @depot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
  
  <table>
  <tr>
    <td align="right" style="width:100px"><%= f.label t('.depot_name') %></td>
    <td><%= f.text_field :dep_name %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right"><%= f.label t('.depot_description') %></td>
    <td><%= f.text_field :dep_desc %></td>
  </tr>
   <tr><td><br></td></tr>
  <tr>
    <td align="right"><%= f.label t('.depot_type') %></td>
    <td><%= f.select :dep_type, DepotsHelper::TYPE %></td>
  </tr>
  <tr><td><br></td></tr>
  <tr>
    <td align="right"><%= f.label t('.depot_status') %></td>
    <td><%= f.select :dep_status, DepotsHelper::STATUS %></td>
  </tr>
  </table>
   
  <br>
  <button type="submit" class="btn btn-primary btn-small"><%= t('.submit') %></button>
  <br>
  <%= link_to t('.cancel'), :back %>
  
<% end %>

app/views/depots/_form_popup.html.erb
<%= form_for([@depot, @depot.packages.build]) do |f| %>

   <table>
    <tr>
      <td align="left" style="width:100px"><%= f.label :name %></td>
      <td><%= f.text_field :pkg_name %></td>
    </tr>
    <tr><td><br></td></tr>
    <tr>
      <td align="left" style="width:100px"><%= f.label :description %></td>
      <td><%= f.text_field :pkg_desc %></td>
    </tr>
    <tr><td><br></td></tr>
    <tr>
      <td align="left" style="width:100px"><%= f.label :type %></td>
      <td><%= f.select :pkg_type, PackagesHelper::TYPE %></td>
    </tr>
    <tr><td><br></td></tr>
    <tr>
      <td align="left" style="width:100px"><%= f.label :version %></td>
      <td><%= f.text_field :pkg_version %></td>
    </tr>
    <tr><td><br></td></tr>
    <tr>
      <td align="left" style="width:100px"><%= f.label t('.status') %></td>
      <td><%= f.select :pkg_status, PackagesHelper::STATUS %></td>
    </tr>
    </table>
   <br>
    <br>
   <button type="submit" class="btn btn-primary btn-small"><%= t('.submit') %></button>
   <br>
   <%= link_to t('.cancel') %>

<% end %>

app/views/depots/edit.html.erb
<div class="well" style="width:95%">
  
<h3><%= t('.edit_depot') %></h3><br>

<% unless notice.nil? %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<%= render 'form' %>

</div>

app/views/depots/index.html.erb
<h3><%= image_tag( "depots.png", :border => 0, :valign => "middle" ) %> <%= t('.depot_details') %> <%= link_to image_tag('tooltip12x12.png', :border => 0, :align => "top"), nil, title: t('.depot_tooltip'), rel: 'popover' %></h3>

<% unless notice.nil? %>
  <div class="container center alert alert-success"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="alert"><%= flash[:alert] %></p>
  </div>
<% end %>
 
<table class="table table-striped table-bordered table-condensed">
  <tr style="background-color: #44721e">  
    <th style="background-color: #91b96f"><%= sortable t('.depot_name') %></th> 
    <th style="background-color: #91b96f"><%= t('.depot_description') %></th>
    <th style="text-align: center; background-color: #91b96f"><%= t('.depot_type') %></th>
    <% if (session[:user_role] == "admin") %>
    <th style="width:200px; text-align: left; background-color: #91b96f"><%= t('.depot_url') %></th>
    <% end %>
    <th style="text-align: center; background-color: #91b96f"><%= t('.depot_status') %></th>
    <th style="text-align: center; background-color: #91b96f" colspan=3><%= t('.actions') %></th>
  </tr>

<% @depots.each do |depot| %>
 <% if user_HasCredToDepot(depot.id, session[:user_id]) %>
  <tr>
    <td><%= depot.dep_name %></td>
    <td><%= depot.dep_desc %></td>
    <td style="text-align: center"><%= raw get_DepotTypeText(depot.dep_type) %></td>
    <% if (session[:user_role] == "admin") %>
    <td><%= depot.dep_url %></td>
    <% end %>
    <td style="text-align: center"><%= raw get_DepotStatusText(depot.dep_status) %></td>
    <td style="text-align: center;width:100px"><%= link_to t('.show'), depot, :method => "get", :class => "btn btn-primary btn-mini" %></td>
    <td style="text-align: center;width:100px"><% if user_HasWriteAccess(depot.id, session[:user_id]) %><%= link_to t('.edit'), edit_depot_path(depot), :method => "get", :class => "btn btn-warning btn-mini" %><% else %><%= link_to t('.edit'), nil, title: t('.depot_no_cred'), rel: 'popover', :class => "btn btn-default btn-mini" %><% end %></td>
    <td style="text-align: center;width:100px"><% if user_HasWriteAccess(depot.id, session[:user_id]) %><%= link_to t('.destroy'), depot, confirm: t('.confirm'), method: :delete, :class => "btn btn-danger btn-mini" %><% else %><%= link_to t('.destroy'), nil, title: t('.depot_no_cred'), rel: 'popover', :class => "btn btn-default btn-mini" %><% end %></td>
  </tr>
 <% end %>
<% end %>

</table>

<br />

<% if user_HasCanCreateDepot(session[:user_id]) %>
  <%= button_to t('.add_depot'), new_depot_path, :class => "btn btn-primary btn-small" %>
<% end %>

app/views/depots/new.html.erb
<div class="well" style="width:95%">
  
<h3><%= t('.add_depot') %></h3><br>

<% unless notice.nil? %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<%= render 'form' %>

</div>

app/views/depots/show.html.erb
<h3><%= image_tag( "depots.png", :border => 0, :valign => "middle" ) %> <%= t('.depot_details') %> </h3>

<% unless notice.nil? %>
  <div class="container center alert alert-success"  style="width:500px">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="container center alert alert-error"  style="width:500px">
    <p id="alert"><%= flash[:alert] %></p>
  </div>
<% end %>

<table class="table table-striped table-bordered table-condensed">
<tr style="background-color: #44721e">
  <th style="background-color: #91b96f"><%= t('.depot_name') %></b></td>
  <th style="background-color: #91b96f"><%= t('.depot_description') %></b></td>
  <th style="background-color: #91b96f; text-align: center"><%= t('.depot_type') %></b></td>
  <th style="background-color: #91b96f"><%= t('.depot_url') %></b></td>
  <th style="text-align: center; background-color: #91b96f"><%= t('.depot_status') %></th>
</tr>
<tr>
  <td align="right"><b><%= @depot.dep_name %></td>
  <td><%= @depot.dep_desc %></td>
  <td style="text-align: center"><%= raw get_DepotTypeText(@depot.dep_type) %></td>
  <td><%= @depot.dep_url %></td>
  <td style="text-align: center"><%= raw get_DepotStatusText(@depot.dep_status) %></td>
</tr>
</table>

<h3><%= image_tag( "packages.png", :border => 0, :valign => "middle" ) %> <%= t('.packages') %> <%= link_to image_tag('tooltip12x12.png', :border => 0, :align => "top"), nil, title: t('.package_tooltip'), rel: 'tooltip' %></h3>
<table class="table table-striped table-bordered table-condensed">
<tr style="background-color: #44721e">
  <th style="background-color: #91b96f"><%= t('.package_name') %></b></td>
  <th style="background-color: #91b96f"><%= t('.package_desc') %></b></td>
  <th style="background-color: #91b96f; text-align: center;width:50px"><%= t('.package_type') %></b></td>
  <th style="background-color: #91b96f; text-align: center;width:50px"><%= t('.package_version') %></b></td>
  <th style="background-color: #91b96f; text-align: left;width:200px"><%= t('.package_url') %></b></td>
  <th style="background-color: #91b96f; text-align: center;width:50px"><%= t('.package_status') %></b></td>
  <th style="text-align: center; background-color: #91b96f" colspan=3><%= t('.actions') %></th>
</tr>
<% @depot.packages.each do |package| %>
<tr>
  <td><%= package.pkg_name %></td>
  <td><%= package.pkg_desc %></td>
  <td style="text-align: center"><%= raw get_PackageTypeText(package.pkg_type) %></td>
  <td style="text-align: center;width:50px"><%= package.pkg_version %></td>
  <td style="text-align: left;"><%= package.pkg_url %></td>
  <td style="text-align: center"><%= raw get_PackageStatusText(package.pkg_status) %></td>
  <td style="text-align: center;width:30px"><%= button_to t('.show'), [package.depot, package], :depot_id => @depot.id, :method => "get", :class => "btn btn-mini" %></td>
  <td style="text-align: center;width:30px"><%= button_to t('.edit'), edit_package_path(package), :package_id => package.id, :method => "get", :class => "btn btn-mini" %></td>
  <td style="text-align: center;width:30px"><%= button_to t('.destroy'), [package.depot, package], confirm: t('.confirm'), method: :delete, :class => "btn btn-mini" %></td>
</tr>
<% end %>
</table>

<%= link_to t('.add_package'), new_depot_package_path(@depot), :class => "btn btn-primary btn-small" %>
<br>
<%= link_to t('.back'), :back %>